swagger: "2.0"
info:
  version: "1.0"
  title: My tutorial project
  description: An app to manage Tutorials
host: localhost:3000
basePath: /
tags:
  - name: Tutorials
    description: API for Tutorials in the system
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /tutorial:
    get:
      tags:
        - Tutorials
      summary: Get all tutorials in system
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/Tutorial"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/500Response"
    post:
      summary: Create tutorials in system
      tags:
        - Tutorials
      parameters:
        - name: Tutorials
          in: body
          description: Tutorial that we want to create
          schema:
            $ref: "#/definitions/TutorialCreateBody"
      produces:
        - application/json
      responses:
        "201":
          description: New tutorials is created
          schema:
            $ref: "#/definitions/TutorialCreateBody"
        "400":
          description: "Invalid Tutorial Id"
          schema:
            $ref: "#/definitions/400Response"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/500Response"

  /tutorial/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: ID of the tutorial
        type: string
    delete:
      summary: Delete tutorial with given ID
      tags:
        - Tutorials
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/Tutorial"
        "404":
          description: "Tutorial not found"
          schema:
            $ref: "#/definitions/404Response"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/500Response"

    patch:
      summary: Update tutorial with give ID
      tags:
        - Tutorials
      parameters:
        - name: Tutorials
          in: body
          description: Tutorial that we want to Update
          schema:
            $ref: "#/definitions/TutorialCreateBody"
      responses:
        "204":
          description: Tutorial is updated
          schema:
            $ref: "#/definitions/Tutorial"
        "400":
          description: "Invalid Tutorial Id"
          schema:
            $ref: "#/definitions/400Response"
        "404":
          description: "Tutorial not found"
          schema:
            $ref: "#/definitions/404Response"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/500Response"
    get:
      tags:
        - Tutorials
      summary: Get tutorial By ID
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/Tutorial"
        "404":
          description: "Tutorial not found"
          schema:
            $ref: "#/definitions/404Response"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/500Response"
  /user:
    post:
      tags:
        - User
      summary: Register user into system
      parameters:
        - name: user
          in: body
          description: Create user
          schema:
            $ref: "#/definitions/user"
      responses:
        "201":
          description: OK
          schema:
            $ref: "#/definitions/user"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/500Response"
  /user/reset-password:
    get:
      summary: Get a password reset token for an email address and send it to the user
      tags:
        - User
      parameters:
        - name: email
          in: path
          required: true
          description: id of the User
          type: string
      responses:
        "200":
          description: otp send on email
          schema:
            $ref: "#/definitions/user"
        "400":
          description: "Invalid user Email"
          schema:
            $ref: "#/definitions/400Response"
        "404":
          description: "User not found"
          schema:
            $ref: "#/definitions/404Response"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/500Response"
    post:
      summary: Process the password reset.
      tags:
        - User
      parameters:
        - name: User
          in: body
          description: User password reset though id using ott
          schema:
            $ref: "#/definitions/userResetPassword"
      responses:
        "204":
          description: Password is updated
          schema:
            $ref: "#/definitions/user"
        "400":
          description: "Invalid token"
          schema:
            $ref: "#/definitions/400Response"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/500Response"

  /user/forgot-password:
    parameters:
      - name: email
        in: path
        required: true
        description: email of the User
        type: string
    get:
      summary: forgot password using user Id though email otp
      tags:
        - User
      responses:
        "200":
          description: otp send on email
          schema:
            $ref: "#/definitions/user"
        "400":
          description: "Invalid user email"
          schema:
            $ref: "#/definitions/400Response"
        "404":
          description: "User not found"
          schema:
            $ref: "#/definitions/404Response"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/500Response"

  /user/login:
    get:
      tags:
        - User
      summary: Login user into system
      parameters:
        - name: "username"
          in: "query"
          description: "The user name for login"
          required: true
          type: "string"
        - name: "password"
          in: "query"
          description: "The password for login in clear text"
          required: true
          type: "string"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/userLogin"
        "404":
          description: "Tutorial not found"
          schema:
            $ref: "#/definitions/404Response"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/500Response"

definitions:
  Tutorial:
    required:
      - _id
      - title
      - description
      - createdAt
      - updatedAt
      - published
    properties:
      _id:
        type: string
        format: uuid
        uniqueItems: true
      title:
        type: string
      description:
        type: string
      published:
        type: boolean
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time

  TutorialCreateBody:
    required:
      - title
      - description
      - published
    properties:
      title:
        type: string
      description:
        type: string
      published:
        type: boolean

  500Response:
    type: object
    required:
      - message
    properties:
      message:
        type: string

  404Response:
    type: object
    required:
      - message
    properties:
      message:
        type: string

  400Response:
    type: object
    required:
      - message
    properties:
      message:
        type: string

  user:
    required:
      - firstname
      - lastname
      - username
      - email
      - password
    properties:
      firstname:
        type: string
      lastname:
        type: string
      username:
        type: string
      email:
        type: string
      password:
        type: string

  userResetPassword:
    required:
      - password
      - token
    properties:
      password:
        type: string
      token:
        type: string

  userLogin:
    required:
      - username
      - password
    properties:
      username:
        type: string
      password:
        type: string
